//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_MVCApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pet
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pet()
        {
            this.UploadedFiles = new HashSet<UploadedFile>();
        }

        public int IDPet { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage = "Pet name can not be longer then 20")]
        public string PetName { get; set; }
        [Required]
        [MaxLength(50, ErrorMessage = "Pet species can not be longer then 50")]
        public string Species { get; set; }
        [Required]
        [Range(0, 30, ErrorMessage = "Pet age can not be less than 0 and more than 30")]
        public int Age { get; set; }
        [Required]
        [Range(0, 9999, ErrorMessage = "Vet ID has to be a positive number")]
        public int VeterinarianIDVeterinarian { get; set; }
        [Required]
        [Range(0, 9999, ErrorMessage = "Owner ID has to be a positive number")]
        public int OwnerIDOwner { get; set; }

        public virtual Veterinarian Veterinarian { get; set; }
        public virtual Owner Owner { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadedFile> UploadedFiles { get; set; }
    }
}
