//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PPPK_MVCApp
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Veterinarian
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Veterinarian()
        {
            this.Pets = new HashSet<Pet>();
        }
    
        public int IDVeterinarian { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage ="First name can not be longer then 20")]
        public string FirstName { get; set; }
        [Required]
        [MaxLength(20, ErrorMessage ="Last name can not be longer then 20")]
        public string LastName { get; set; }
        [Required]
        [MaxLength(30, ErrorMessage ="Email can not be longer then 30")]
        public string Email { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pet> Pets { get; set; }
    }
}
